[package]
name = "chipper"
authors = ["raddari"]
version = "0.1.0"
edition = "2018"
description = "Chip8 interpreter and debugger!"
repository = "https://github.com/raddari/chipper"
license = "MIT"

[dependencies]
rand = "0.8.4"

[dev-dependencies]
pretty_assertions = "1.0.0"
