#[allow(non_camel_case_types)]
pub enum Opcode {
    OP_00E0 {},
    OP_00EE {},
    OP_0nnn { nnn: u16 },
    OP_1nnn { nnn: u16 },
    OP_2nnn { nnn: u16 },
    OP_3xkk { x: usize, kk: u8 },
    OP_4xkk { x: usize, kk: u8 },
    OP_5xy0 { x: usize, y: usize },
    OP_6xkk { x: usize, kk: u8 },
    OP_7xkk { x: usize, kk: u8 },
    OP_8xy0 { x: usize, y: usize },
    OP_8xy1 { x: usize, y: usize },
    OP_8xy2 { x: usize, y: usize },
    OP_8xy3 { x: usize, y: usize },
    OP_8xy4 { x: usize, y: usize },
    OP_8xy5 { x: usize, y: usize },
    OP_8xy6 { x: usize, y: usize },
    OP_8xy7 { x: usize, y: usize },
    OP_8xyE { x: usize, y: usize },
    OP_9xy0 { x: usize, y: usize },
    OP_Annn { nnn: u16 },
    OP_Bnnn { nnn: u16 },
    OP_Cxkk { x: usize, kk: u8 },
    OP_Dxyn { x: usize, y: usize, n: usize },
    OP_Ex9E { x: usize },
    OP_ExA1 { x: usize },
    OP_Fx07 { x: usize },
    OP_Fx0A { x: usize },
    OP_Fx15 { x: usize },
    OP_Fx18 { x: usize },
    OP_Fx1E { x: usize },
    OP_Fx29 { x: usize },
    OP_Fx33 { x: usize },
    OP_Fx55 { x: usize },
    OP_Fx65 { x: usize },
}
